### ISSUE TITLE
Setting the map div to be 100% gives a height of 0px

### ISSUE THREAD

**Issue by smsm1** [mlevans/leaflet-hash#11]
If I set the map height in CSS to be 100% or any percentage for that matter, the height is computed to be 0 after adding this plugin for the permalink. I don't expect this to happen, nor do I expect to have to set the height either via js or a fixed pixel height.

**Comment by calvinmetcalf** [comment]
that's a leaflet thing but you have to set the following css to make a full page map

``` css
html { height: 100% }
body { height: 100%; margin: 0; padding: 0;}
#map{ height: 100% }
```
